### ISSUE TITLE
Autplay on connect

### ISSUE THREAD

**Issue by Grimblag** [Splamy/TS3AudioBot#1002]
**Describe the problem**
I wish, that the bot autoplays the latest, or a given radio stream on connect.
I think its a onconnect thing in toml?

**Comment by Flakebi** [comment]
Right, in the ts3audiobot.toml, set
```toml
[events]
onconnect = "!play 'link'"
```
