### ISSUE TITLE
How can I disable commands via URL?

### ISSUE THREAD

**Issue by itseyup** [Splamy/TS3AudioBot#1005]
**Describe the problem**
I want to disable command use via URL like this;
http://SERVER_IP:58913/api/bot/use/0/(/bot/name/AudioBot)

**Comment by Flakebi** [comment]
You need to disable the web api in the `ts3audiobot.toml`.
Should be something like
```toml
[api]
enabled = false # Set to *false* here
```
(I didn’t check the exact names).
