### ISSUE TITLE
Does the bot work with the new yt-dlp?

### ISSUE THREAD

**Issue by CODEX-cpp** [Splamy/TS3AudioBot#1031]
Since youtube-dl has been discontinued for years now, the community has created the new yt-dlp. does the bot work with this new system?

**Comment by Flakebi** [comment]
Yes it does, you just have to configure the path to yt-dlp in `ts3audiobot.toml`:
```toml
[tools]
#Path to the youtube-dl binary or local git repository.
youtube-dl = { path = "yt-dlp" }
```
