### ISSUE TITLE
About omitting the local music path

### ISSUE THREAD

**Issue by ctt-t** [Splamy/TS3AudioBot#1042]
I added some music locally, but if I chat with the bot to change the song needs to be sent! Play C: / Users/Administrator/Desktop/music /. Mp3, is there can omit the path way

**Comment by Flakebi** [comment]
You can change that via a command: `!settings global set factories.media.path C:/Users/Administrator/Desktop/music`

Or in the `ts3audiobot.toml` in this paragraph:
```toml
[factories]
#The default path to look for local resources.
media = { path = "C:/Users/Administrator/Desktop/music" }
```
