### ISSUE TITLE
Auto Mute

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#278]
Stop the Music if nobody listen, to Save Bandwith

**Comment by Caeas** [comment]
Will this feauture implemented in a future release? Would also think thats nice.

**Comment by Splamy** [comment]
I've put it on the 0.11.0 roadmap. Lets see, when I get to it.
You can check the roadmaps here https://github.com/Splamy/TS3AudioBot/milestones

**Comment by Bluscream** [comment]
https://github.com/Bluscream/TS3AudioBotPlugins/blob/develop/AutoPause/Plugin.cs

**Comment by Caeas** [comment]
ok great thx much u2

**Comment by Splamy** [comment]
The bot now has events to freely configure when left alone or joined again.
```toml
[events]
#...

#Called when the last client leaves the channel of the bot. Delay can be specified
onalone = "!stop"
#Specifies how long the bot has to be alone until the 'onalone' event gets fired.
#You can specify the time in the ISO-8601 format with quotation marks "PT30S" or like: 15s, 1h, 3m30s
alone_delay = "10s"
#Called when the bot was alone and a client joins his channel. Delay can be specified.
onparty = "!play"
#Specifies how long the bot has to be alone until the 'onalone' event gets fired.
#You can specify the time in the ISO-8601 format with quotation marks "PT30S" or like: 15s, 1h, 3m30s
party_delay = "0s"
```
