### ISSUE TITLE
Musicbot request

### ISSUE THREAD

**Issue by iiAlphaWolf** [Splamy/TS3AudioBot#338]
Hey splamy,

So let me explain what if the music bot isnt being used for like 15 minitues and then it moves to AFK channel. when someone wants music they type in chat !music and a musicbot in afk waiting will join.

this way i can host/ run multiple music bots in the server and people can request a waiting one!?

**Comment by dzinks2009** [comment]
It would be possible, but you'd probably have to edit the source code a lot. However, you can always create a query bot.

**Comment by Splamy** [comment]
You could simply write a plugin which does that.
Btw you have already requested kinda the same feature before: #135 should I close that?

**Comment by iiAlphaWolf** [comment]
Ya sorry, close this one leave the other one open :D

**Comment by P-Kito** [comment]
![image](https://user-images.githubusercontent.com/876676/43426041-c70c4de8-9454-11e8-93b8-52a3dd6ce3ea.png)

I made it like this. People have privileges to move them and make them play music.
I also have a Java Bot running, which assigns levels according to connected time. It also moves the music bots back if they are alone in a channel for 10 minutes or have idle time of 10 minutes.

**Comment by Splamy** [comment]
You can do this with the new idle setting, simply set something like this:
```toml
[events]
#Called when the bot does not play anything for a certain amount of time.
onidle = "!bot move 42" # your afk channel id
#Specifies how long the bot has to be idle until the 'onidle' event gets fired.
#You can specify the time in the ISO-8601 format with qutotation marks "PT30S" or like: 15s, 1h, 3m30s
idletime = 15m

# and set this so the bot will join your channel when playing something
[audio]
send_mode = "!xecute (!bot move (!getmy channel)) (!whisper off)"
```
