### ISSUE TITLE
Starting specific bot by parameter?

### ISSUE THREAD

**Issue by CrispyHere** [Splamy/TS3AudioBot#361]
Is this possible to start a specific bot by parameter?

I mean something like 
mono /home/audiobots/TS3AudioBot.exe -bot_ID:1
where ID 1 is ID of the first bot.

**Comment by Splamy** [comment]
Id's are not bound by bot, you have to save a bot as a template with `!bot save <name>` to store settings for a instance.

If you want to automatically run a template at start you can configure it in the settings.
Search for the entry `bots` in the ts3audiobot.toml and add your template like this:

```toml
[bots]
default = { run = true }
mybot1 = { run = false }
# <name> = { run = true }
```
