### ISSUE TITLE
Standard Lautstärke einstellen

### ISSUE THREAD

**Issue by TomGamerTV** [Splamy/TS3AudioBot#372]
Hallo,

Ich möchte bei den Bots Ordner die .toml Datei einstellen. Das er beim starten die gewünschte Lautstärke einstellt. Wie mache ich das genau?

**Comment by Splamy** [comment]
```toml
[bot.audio.volume]
default = 10.0
```
where the 10 for example is the default volume.

**Comment by TomGamerTV** [comment]
Kann man es auch man das es nur 4 sind?

**Comment by TomGamerTV** [comment]
Und wie geht das wenn der Bot sich startet das er sofort den Channel Commander bekommt?

**Comment by Splamy** [comment]
Add it in the connect event:
```toml
[events]
onconnect = "!bot commander on"
```
