### ISSUE TITLE
standard !volume

### ISSUE THREAD

**Issue by gabanzin** [Splamy/TS3AudioBot#445]
Greetings,
I want to know how to setup a standard volume for all songs, because if I change to 1 (for example), on next song the volume just back to 10... thank you

**Comment by P-Kito** [comment]
There is setting in config.

```toml
#When a new song starts the volume will be trimmed to between min and max.
#When the current volume already is between min and max nothing will happen.
#To completely or partially disable this feature, set min to 0 and/or max to 100.
[bot.audio.volume]
default = 2.0
min = 2.0
max = 20
```
