### ISSUE TITLE
Play Music if a user join the channel

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#464]
**Is your feature request related to a problem? Please describe.**
I want to play the User a sound file if the User joins the Support Channel.

**Describe the solution you'd like**
A config option like the option to play on connect

**Comment by Splamy** [comment]
The bot now has events to freely configure when left alone or joined again.
```toml
[events]
#...

#Called when the last client leaves the channel of the bot. Delay can be specified
onalone = "!stop"
#Specifies how long the bot has to be alone until the 'onalone' event gets fired.
#You can specify the time in the ISO-8601 format with quotation marks "PT30S" or like: 15s, 1h, 3m30s
alone_delay = "10s"
#Called when the bot was alone and a client joins his channel. Delay can be specified.
onparty = "!play"
#Specifies how long the bot has to be alone until the 'onalone' event gets fired.
#You can specify the time in the ISO-8601 format with quotation marks "PT30S" or like: 15s, 1h, 3m30s
party_delay = "0s"
```
