### ISSUE TITLE
Configurable reconnect interval via config

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#484]
The current dynamic delay is great for endusers but hosters want to offer their customers custom reconnect intervals in the case of a bad connection or in the case the bot is required for security and has b_client_ignore_antiflood anyway.

```toml
[bot.connect]
reconnect_interval = "auto" # current system
```
```toml
[bot.connect]
reconnect_interval = "30s" # after 30 seconds
```
```toml
[bot.connect]
reconnect_interval = "-1" # never
```

etc...

**Comment by MisterMisiek** [comment]
How to turn it off

**Comment by Bluscream** [comment]
-1 maybe?

**Comment by Splamy** [comment]
```toml
[bot.connect]
reconnect_interval = [] # off
reconnect_interval = ["30s", "1m", "5m"] # intervals
reconnect_interval = ["30s", "1m", "5m", "repeat"] # or "+" or "loop" to repeat last value indefinitely
```

**Comment by Bluscream** [comment]
That's even better :>

**Comment by Bluscream** [comment]
Im thinking about a whole new section for reconnect to allow some other settings maybe :thinking:

```toml
[bot.reconnect]
enabled = true
interval = ["30s", "repeat last"]
onkick = false # wether to also autoreconnect if the bot was kicked
onerror = true # wether to force trying to reconnect if the server is reachable but returned an error (ex: max clones/banned)
```
