### ISSUE TITLE
Hilfe beim WebInterface

### ISSUE THREAD

**Issue by ItzaGamingFail** [Splamy/TS3AudioBot#501]
Hallo ich bräuchte hilfe beim WebInterface coden(bin noch ziemlich neu) ich hab das probiert:

```php
$botid = "0";
$newname = "einfachtest";
$token = "eK1SJm3TgTJsibDMl1dh6kzu8XohmH9q";
$ch = curl_init();
$token = str_replace("+eMpXUNsGG2z/M8OmqmyhgEcyQQ=:ts3ab:", ":", eK1SJm3TgTJsibDMl1dh6kzu8XohmH9q);
$headers = array(
	'Content-Type:application/json',
	'Authorization: Basic '. base64_encode(token)
);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$name = urlencode(newname);
curl_setopt($ch, CURLOPT_URL, "http://79.137.125.52:8191/api/bot/use/$botid/(/bot/name/$name");
curl_exec($ch);
curl_setopt($ch, CURLOPT_URL, "http://79.137.125.52:8191/api/bot/use/$botid/(/settings/set/connect.name/$name");
curl_close($ch)
```

Und als Fehler kam immer das ich keine Rechte dafür habe.

**Comment by Splamy** [comment]
1. please keep issues in english
1. you should redact authentication tokens

```php
$token = "eK1SJm3TgTJsibDMl1dh6kzu8XohmH9q";
//...
$token = str_replace("+eMpXUNsGG2z/M8OmqmyhgEcyQQ=:ts3ab:", ":", eK1SJm3TgTJsibDMl1dh6kzu8XohmH9q);
```
this makes no sense, just put your token in the `$token` variable.
The example for the wiki just removes the `:ts3ab:` realm part which will be deprecated anyway soon
```php
$token = "+eMpXUNsGG2z/M8OmqmyhgEcyQQ=:eK1SJm3TgTJsibDMl1dh6kzu8XohmH9q";
```

Futhermore make sure you assigned all required command permissions in your `rights.toml`
So somethin like at least
```toml
[[rule]]
    uid="+eMpXUNsGG2z/M8OmqmyhgEcyQQ="
    "+"=["cmd.bot.use", "cmd.bot.name", "cmd.settings.set"]
    # or for admins e.g. adding everything:
    # "+" = "*"
```
