### ISSUE TITLE
can't setup bot windows 

### ISSUE THREAD

**Issue by lavid274** [Splamy/TS3AudioBot#505]
Error: You cannot execute 'bot setup'. You are missing the 'cmd.bot.setup' right!

Platform: Windows 10

**Comment by Splamy** [comment]
Go to your rights.toml and set the required values to add yourself all permissions.
There should be a template section that looks like this:
```toml
# Admin rule
[[rule]]
	# Set your admin Group Ids here
	groupid = [ 0 ]
	# And/Or your admin Client Uids here
	useruid = [ "" ]

	"+" = "*"
```
