### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by MisterMisiek** [Splamy/TS3AudioBot#513]
Hi, i have a question about this music bot. When i play any song bot automatically change volume to 10 and i dont know how to save volume or something or set it default to 1 or 2

**Comment by ShadowFM** [comment]
There should be a setting for the volume in the config:

```
#When a new song starts the volume will be trimmed to between min and max.
#When the current volume already is between min and max nothing will happen.
#To completely or partially disable this feature, set min to 0 and/or max to 100.
[bot.audio.volume]
default = 2.0
min = 2.0
max = 20
```

**Comment by MisterMisiek** [comment]
Ok thanks but how can i change config ? (sorry im noob)

**Comment by MisterMisiek** [comment]
[audio]
#When a new song starts the volume will be trimmed to between min and max.
#When the current volume already is between min and max nothing will happen.
#To completely or partially disable this feature, set min to 0 and/or max to 100.
volume = { 2 }
Like that ?

**Comment by Splamy** [comment]
Just as ShadowFM said, either
```toml
[audio.volume]
default = 2.0
min = 2.0
max = 20
```
or
```toml
[audio]
volume = { default = 2 , min = 2 , max = 20 }
```
