### ISSUE TITLE
Webinterface cant connect?

### ISSUE THREAD

**Issue by DennisAncelotti** [Splamy/TS3AudioBot#514]
Hello, i tryed to use the Bot with Webinterface, but it didnt work -> what did i do wrong?
my ts3audiobot.toml:

```toml
[web]
#An array of all urls the web api should be possible to be accessed with.
hosts = ["localhost", "127.0.0.1", "173.***.39.246"]
#The port for the web server.
port = 58913

[web.api]
#If you want to enable the web api.
enabled = true
#Limits the maximum command complexity to prevent endless loops.
command_complexity = 64

[web.interface]
#If you want to enable the webinterface.
enabled = true
#The webinterface folder to host. Leave empty to let the bot look for default locations.
path = "/home/tsbots/TS3AudioBot_develop/WebInterface"
```

**Comment by Splamy** [comment]
what is 'doesnt work'?
what happens when you call `http;//173.***.39.246:58913` ?
white page? no reponse?
Anything in the log when accessing the site?
Did you check your firewall?

**Comment by ShadowFM** [comment]
What does your firewall say if you do
iptables -L ?

It could be that your firewall will block the access

**Comment by DennisAncelotti** [comment]
I restartet the Bot and now the Webinterace works but i become errors on the pages.
Error:
Failed to get system information
Info:


Error:
Error getting bot list
Info:

.
.
.

**Comment by DennisAncelotti** [comment]
now it works but the Interface ignore the tokens (there are only the rights that everybody have, nobody can create Bots)
Error:
Error creating bot
Info:
You cannot execute 'settings create'. You are missing the 'cmd.settings.create' right!

**Comment by Splamy** [comment]
Are you running master or develop?
Have you enabled the api?
Have you assigned all required permissions to the uid using the webinterface? The easiest way would be:
```toml
[[rule]]
uid = "<uid>"
"+" = "*"
```
