### ISSUE TITLE
onidle - For each Bot in one Instance

### ISSUE THREAD

**Issue by NurLutix** [Splamy/TS3AudioBot#520]
Hey,
Would there be the possibility that onidle also found in the bot_default.toml? So you don't have to create a new Instance every time in theory?
And would it be a consideration that onidle can also be controlled via API? (Re-relationship with the Command !idle as an example.)

Greetings.

**Comment by Splamy** [comment]
> Would there be the possibility that onidle also found in the bot_default.toml? So you don't have to create a new Instance every time in theory?

You can set it in each bot, just write:
```toml
[events]
#Called when the bot does not play anything for a certain amount of time.
onidle = "!your comd chain here"
#Specifies how long the bot has to be idle until the 'onidle' event gets fired.
#You can specify the time in the ISO-8601 format with quotation marks "PT30S" or like: 15s, 1h, 3m30s
idletime = 5m
```

> And would it be a consideration that onidle can also be controlled via API? (Re-relationship with the Command !idle as an example.)

You can simply just invoke the same command which is as in the config. You can even get funky and call `!eval (!settings get events.onidle)` which does exactly that. And if you are on develop you can also add an alias for that with: `!alias add idle "!eval (!settings get events.onidle)"`, and then call `!idle` which should be what you want.
Note that aliases are not yet persistently stored yet, so they are lost on restart
