### ISSUE TITLE
Name - For each Bot in one Instance

### ISSUE THREAD

**Issue by NurLutix** [Splamy/TS3AudioBot#521]
Hey,
Would it be possible to set a Standard name? So in the bot_default.toml?
Or is this already possible? (Maybe even with a Command)

Greetings.

**Comment by Splamy** [comment]
```toml
[connect]
#Client nickname when connecting.
name = "Blubi"
```

Is your previous question from the other issue answered? If yes please close it.
