### ISSUE TITLE
How to disable auto subscriptions channel when bot is running into whisper mode?

### ISSUE THREAD

**Issue by cpbpl1230** [Splamy/TS3AudioBot#586]
I really need this option!

**Comment by Splamy** [comment]
can you explain why?

**Comment by cpbpl1230** [comment]
I would like everyone who wants to listen music from bot, he not had to sit on the canal with him. 
Not everyone on the same channel wants to listen to music from the bot.
This is the problem.

**Comment by Splamy** [comment]
Ah now I understand what you want. Set this value in your config like that:
```toml
[bot.audio]
send_mode = "!xecute (!whisper subscription) (!unsubscribe temporary)"
```
