### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by milosz0542** [Splamy/TS3AudioBot#604]
11:17:34.7571| WARN Could not connect: client_version_outdated: the command failed to execute: client version outdated, please update

How I can update teamspeak client version?

**Comment by Flakebi** [comment]
Here is a FAQ entry on how to set the version: https://github.com/Splamy/TS3AudioBot/wiki/FAQ#set-the-client-version

The `3.?.?` version should never be outdated, so setting this version should fix the issue:
```toml
[connect]
client_version = { build = "3.?.? [Build: 5680278000]", platform = "Linux", sign = "Hjd+N58Gv3ENhoKmGYy2bNRBsNNgm5kpiaQWxOj5HN2DXttG6REjymSwJtpJ8muC2gSwRuZi0R+8Laan5ts5CQ==" }
```
