### ISSUE TITLE
Ignore private messages

### ISSUE THREAD

**Issue by Wruczek** [Splamy/TS3AudioBot#614]
Is it possible to make the bot ignore private messages and only listen to server and channel chat?

**Comment by Splamy** [comment]
You could wrap all rules in a rule with a visibility matcher like this:

Example:
```toml
[[rule]]
  groupid="12"
  "+" = "*"
```
And change to:
```toml
[[rule]]
  visibility = ["Channel", "Server"]
  [[rule.rule]]
    groupid="12"
    "+" = "*"
```

It wouldn't really 'ignore' them but you basically cannot request anything in the private chat anymore
