### ISSUE TITLE
Error getting bot list, Failed to get system information

### ISSUE THREAD

**Issue by stillnocake** [Splamy/TS3AudioBot#734]
Hello I'm having some problems listing the bot(s) in the web interface. I always get the 'Error getting bot list' message. Also, the overview gives me the 'Failed to get system information' notice..

The bot is created, I have used !api token and entered the token the bot gave me in the field but it simply would not let me control it using the web interface.

I'm using Debian 10 and don't know anything about mono.

Any help would be much appreciated !

**Comment by Splamy** [comment]
Hey (even though you already added most information) please use our issue template so you don't miss something like bot version which is often helpful for us.

About your problem, make sure you have added your teamspeak uid (the one you created the token with, which also is in the token) to the rights.toml file into the admin group (or an equivalent group).

The default admin rule looks something like this:
```toml
[[rule]]
	useruid = [
		"Splamy36QrG5AkF4uoS/h0fpHr0=",
		"y1T5fD4ypVwd7eQvu6ryhvn8PPg=",
		# add uid's here as you like
	]

	"+" = "*"
```

Since the api currently required many different permissions it's the easiest to just assign all permissions via uid. We want to make web permissions better manageable with the permission rework (#651) which is targeted for 0.12.0
