### ISSUE TITLE
Missing Rights

### ISSUE THREAD

**Issue by RealPwned** [Splamy/TS3AudioBot#742]
Hi,
i want to change the Discription of the Bot. But i receive missing "cmd.bot.description.set"

[](https://prnt.sc/ral6xf)

[](https://prnt.sc/ral7wt)

Thank you

**Comment by Splamy** [comment]
Create or extend a permission rule in your `rights.toml` to give you the permission `"cmd.bot.description.set"`

A basic rule could look like this
```toml
[[rule]]
uid = "<your uid>"
"+" = [ "cmd.bot.description.set" ]
```

Also check out our examples in the wiki https://github.com/Splamy/TS3AudioBot/wiki/Rights#examples
