### ISSUE TITLE
Rights system rework

### ISSUE THREAD

**Issue by Splamy** [Splamy/TS3AudioBot#79]
**Progress**
Working Matcher:
- [x] ClientUid
- [x] ServerGroup
- [x] ChannelGroup
- [x] Visibility
- [x] Bot/Instance
- [x] Teamspeak 3 permissions
- [x] Api (Bool)
- [x] Api (Token)

**Problems**:
- The current rights system with Public/Private/Any/Admin is very limited and provides no configurability for the user.
- Many modules are bound to use certain userids and cant operate without. This limits the expandability of the code [open]
- The current system is limited to only one server

**Solutions/Ideas**:
The new system should fix those problems. The following constructs should help with this.
- We don't want to reinvent the wheel with a second rights system parallel to the one of teamspeak 3. Therefore rights are again bound to _ts3 user groups_ but can now also be sub-specified
- The rights config file will use [toml](https://github.com/toml-lang/toml) as a standartized and widespread language which can be modified by other tools and already has stable libraries

*Rights language syntax prototype v0.2 Example*:
```toml
# Rules on level 0 layer affect all bot instances across all server.
# Keep in mind that those rights can still be overridden in any rule.

# the "+" is a list of all rights to be added
"+" = [ "cmd.help" ]
# the "-" is a list of all rights to be denied
"-" = "cmd.quit"

# You can declare groups with $name to structurize certain rights together
["$admin"]
	"+" = [ "cmd.play" ]
	"-" = [ "cmd.help", "cmd.pm" ]

# This is the first rule
# The keys have no fixed order, but we suggest you to keep it at least consistent
# Each rule can contain so called "includes", "matches" and "delcarations"
[[rule]]
	# This is a include, which means that this group will have all
	# "+" and "-" delcarations of the included groups
	include = "$admin"
	
	# These are the so called matches
	# This rule will be applied to a user if *any* of them matches, so for ex.
	# The bot/user talks on the server with the hostname "splamy.de"
	host = "splamy.de"
	# The user has the uid "gMVR34YE7I/r37+mgmYORV="
	useruid = [ "gMVR34YE7I/r37+mgmYORV=" ]
	# The user is within the group with id "30"
	groupid = 30
	# The user has the specified ts3 right or meets the expression requirement
	perm = [ "b_client_server_textmessage_send",
	         "i_filebrowser_upload>=50" ]

	# These are the declarations (as seen at the start already)
	"+" = [ "cmd.play" ]
	"-" = [ "cmd.help", "cmd.pm" ]

[[rule]]
	host = [ "flakebi.de", "192.168.0.1" ]
	groupid = 30
	perm = [ "b_client_server_textmessage_send",
	         "i_filebrowser_upload>=50" ]

	include = "$admin"
	"+" = [ "cmd.play" ]
	"-" = [ "cmd.help", "cmd.pm" ]

	# A nested group is only visible to rules on the same level and lower
	[rule."$all"]
		include = "$admin"
		"+" = "cmd.play"
		"-" = [ "cmd.help", "cmd.*" ]

	[[rule.rule]]
		groupid = [ 30, 31 ]
		include = [ "$admin", "$all" ]
		"+" = [ "cmd.play" ]
		"-" = [ "cmd.help", "cmd.pm" ]

	[[rule.rule]]
		groupid = 35
		include = "$admin"
		"+" = [ "cmd.play" ]
		"-" = [ "cmd.help", "cmd.pm" ]

# Whenever a right is specified more detailed (for ex. from [rule] =lvl1 to [rule.rule] =lvl3)
# the more detailed specification (lvl3) will override the previous one.

# Each rule consists of 2 levels:
# (n-1 = all rules build up from higher levels)
#  n   = all rules included with the 'include' directive
#  n+1 = all rules declared with '+' and '-'
# This conveniently allows to expand rules with groups while still giving the option
# to make the final changes in the rule itself

# When two rules with the same level are applied to a used they will be merged
# but "-" declarations will override "+" delcarations of the same level or lower

# A group name must be always uniqely idetifiable.
# This means when for ex. we have a group ["$a"], and [rule] declares a group [rule."$a"],
# those "$a"s are indistinguishable, therefore this is disallowed.
# On the other hand when one [rule] declares [rule."$a"], and another [rule] does the same,
# both "$a"s are only visible in that certain [rule] respectively, so this is valid.

# For convenience all keys can have either single values or array of values
```
