### ISSUE TITLE
Bot - Send Massage

### ISSUE THREAD

**Issue by Silencesteal** [Splamy/TS3AudioBot#807]
Hello Community, 

how can the bot send a message to all players in the channel as soon as he enters the channel?
or by writing to the bot?

**Comment by Flakebi** [comment]
Hi,

You can find an overview of all commands with `!help` and `!help all` and also here: https://tab.splamy.de/openapi/index.html

I’m not perfectly sure what you want to do, so here are some example commands to write messages:
`!print Hi everyone`
`!pm channel Hello channel`

In the settings, you can e.g. use this:
```toml
[bot.events]
#Called when the bot was alone and a client joins his channel. Delay can be specified.
onparty = "!pm channel Hello channel"
```
