### ISSUE TITLE
How to multiple command to [events] onconnect?

### ISSUE THREAD

**Issue by froland20** [Splamy/TS3AudioBot#827]
Hello!

How can I use multiple commands?

I tried this on the bot.toml but it's not working.

This works:
[events]
onconnect = "!bot move '397'"

But this is not working:
onconnect = "!bot move '397'" "!play 'link'"

Unfortunately, it doesn't work in a new line either.

Someone can help me how is it working the multiple commands in one line?

**Comment by Flakebi** [comment]
You can use the `!xecute` command to chain multiple commands (note: starts with an x, not e).

```toml
[events]
onconnect = "!x (!bot move '397') (!play 'link')"
```
