### ISSUE TITLE
Announce the title of the music automatically

### ISSUE THREAD

**Issue by Edith445544986** [Splamy/TS3AudioBot#890]
Hi ! I've been looking for some time for the bot to automatically announce music to the channel...

**Comment by Flakebi** [comment]
Hi, the bot has a `onsongstart` event that can be used for that:
```toml
[bot.events]
onsongstart = "!pm channel (!song)"
```

Or to set via command, `!settings set events.onsongstart "!pm channel (!song)"` for a bot, or
`!settings global set bot.events.onsongstart "!pm channel (!song)"` globally (taken from #834).
