### ISSUE TITLE
Admin Group ID attached to the server & Changing the Admin Group ID from WebInterface

### ISSUE THREAD

**Issue by itseyup** [Splamy/TS3AudioBot#998]
**Describe the solution you'd like**
That would be good if the Admin Group ID would be attached to the server. I mean ID-1 Bot has an admin group with "7", but ID-2 Bot has an admin group with "8". I hope that I describe it.

**Describe the solution you'd like 2**
Changing the Admin Group ID from WebInterface.

**Comment by Flakebi** [comment]
Hi, you can ‘and’ rules by nesting them.
So, it’s possible to give permissions to group x on server a and group y on server b.
`rights.toml` from https://github.com/Splamy/TS3AudioBot/wiki/Rights#example-2 (Example 2):
```toml
# This rule matches when we use any bot which is connected to 'myts.com'
[[rule]]
host = "myts.com"

    [[rule.rule]]
    # Match for all users in the server group '6'
    groupid = 6
    # we could also write:
    # groupid = [ 6 ]
    # That way you can add more groups like [ 6, 7, 10, 42, ... ]

    # The permissions for !play and !add
    "+" = [ "cmd.play", "cmd.add" ]

# This rule matches when we use any bot which is connected to 'otherts.net'
[[rule]]
host = "otherts.net"

    [[rule.rule]]
    # Match for all users in the server group '10'
    groupid = 10

    # The permissions for !play and !add
    "+" = [ "cmd.play", "cmd.add" ]
```

That’s not possible from the webinterface though.
